# Generated by Django 5.2.17 on 2026-08-13 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='адрес')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='показывать в меню')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.section', verbose_name='родительский раздел')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='адрес')),
                ('lead', models.TextField(blank=True, verbose_name='краткое описание')),
                ('body', models.TextField(blank=True, help_text='Допускается HTML-разметка', verbose_name='содержимое')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликована')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='core.section', verbose_name='раздел')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы',
                'ordering': ['order', 'title'],
            },
        ),
    ]
