# Generated by Django 5.2.17 on 2026-08-13 06:38

import django.db.models.deletion
import telemetry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='код')),
                ('api_key', models.CharField(default=telemetry.models.generate_api_key, max_length=64, unique=True, verbose_name='ключ API')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя связь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'устройство',
                'verbose_name_plural': 'устройства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Идентификатор в пакете от контроллера, напр. s1', max_length=32, verbose_name='ключ')),
                ('label', models.CharField(blank=True, help_text='Понятное имя, напр. Цех 1 / вход', max_length=100, verbose_name='название')),
                ('unit', models.CharField(default='°C', max_length=16, verbose_name='единица')),
                ('color', models.CharField(blank=True, help_text='HEX, напр. #e2574c', max_length=7, verbose_name='цвет на графике')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='telemetry.device', verbose_name='устройство')),
            ],
            options={
                'verbose_name': 'датчик',
                'verbose_name_plural': 'датчики',
                'ordering': ['device', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.BigIntegerField(verbose_name='номер пакета')),
                ('ts', models.DateTimeField(verbose_name='время замера')),
                ('value', models.FloatField(verbose_name='значение')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='принято сервером')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.sensor', verbose_name='датчик')),
            ],
            options={
                'verbose_name': 'замер',
                'verbose_name_plural': 'замеры',
                'ordering': ['-ts'],
            },
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('device', 'key'), name='uniq_sensor_per_device'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['sensor', '-ts'], name='idx_reading_sensor_ts'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('sensor', 'seq'), name='uniq_reading_per_seq'),
        ),
    ]
