# Generated by Django 5.2.17 on 2026-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reading',
            name='uniq_reading_per_seq',
        ),
        migrations.AddField(
            model_name='reading',
            name='boot',
            field=models.BigIntegerField(default=0, verbose_name='запуск контроллера'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('sensor', 'boot', 'seq'), name='uniq_reading_per_boot_seq'),
        ),
    ]
