# Generated by Django 5.2.17 on 2026-08-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_remove_reading_uniq_reading_per_seq_reading_boot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='report_interval_sec',
            field=models.PositiveIntegerField(default=180, help_text='Как часто контроллер шлёт данные. По нему считается, потеряна ли связь, и когда показания на сайте считать несвежими.', verbose_name='интервал замеров, с'),
        ),
    ]
