# Generated by Django 5.2.17 on 2026-08-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_device_report_interval_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='alarm_above',
            field=models.FloatField(blank=True, help_text='Значение, на котором краснота достигает предела.', null=True, verbose_name='порог «перегрев»'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='warn_above',
            field=models.FloatField(blank=True, help_text='С этого значения число начинает краснеть. Пусто — не подкрашивать.', null=True, verbose_name='порог «выше нормы»'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='color',
            field=models.CharField(blank=True, help_text='Оставьте пустым — цвет назначится по палитре. HEX вида #2a78d6 переопределит его.', max_length=7, verbose_name='цвет на графике'),
        ),
    ]
