# Generated by Django 5.2.17 on 2026-08-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_sensor_alarm_above_sensor_warn_above_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='site_timezone',
            field=models.CharField(default='Europe/Rome', help_text='Где физически стоят датчики. Например Europe/Rome для Сардинии, Asia/Krasnoyarsk для Красноярска.', max_length=64, verbose_name='часовой пояс площадки'),
        ),
    ]
